KNOWN_MAPPINGS = [
    {'entry': '12 Jornales, 3 Cargas motosierra', 'category': 'MANO DE OBRA'},
    {'entry': '19 Jornales y 8 tareas', 'category': 'MANO DE OBRA'},
    {'entry': '5 Tanques en los limones', 'category': 'MANO DE OBRA'},
    {'entry': '6 Jornales de Chapeo', 'category': 'COSECHA'},
    {'entry': '8 Jornales de chapeo Orilla de rancho viejo', 'category': 'COSECHA'},
    {'entry': 'Agroindustrias Raiker, S. de R.L.', 'category': 'AGROQUIMICOS'},
    {'entry': 'Agroinsumo', 'category': 'AGROQUIMICOS'},
    {'entry': 'Agroinsumos', 'category': 'AGROQUIMICOS'},
    {'entry': 'Agroinsumos papaloapan', 'category': 'AGROQUIMICOS'},
    {'entry': 'Agros de la cuenca', 'category': 'AGROQUIMICOS'},
    {'entry': 'Aplicación de 75 sacos y 8 tanques', 'category': 'MANO DE OBRA'},
    {'entry': 'Bombas y motosierras Vargas', 'category': 'MANO DE OBRA'},
    {'entry': 'Cabezal puente', 'category': 'MANO DE OBRA'},
    {'entry': 'Cadena comercial Oxxo, S.A. de C.V.', 'category': 'COMIDA'},
    {'entry': 'Cadena comercial, Oxxo, S.A. de C.V.', 'category': 'COMIDA'},
    {'entry': 'Capufe', 'category': 'MANO DE OBRA'},
    {'entry': 'Comision federal de electricidad', 'category': 'GASOLINA'},
    {'entry': 'Compra de agroinsumos', 'category': 'AGROQUIMICOS'},
    {'entry': 'Desmonte', 'category': 'COSECHA'},
    {'entry': 'Distribuidora de agroquimicos del golfo, .S.A. de .C.V', 'category': 'AGROQUIMICOS'},
    {'entry': 'Distribuidora de Agroquimicos del Golfo, S.A. de C.V.', 'category': 'AGROQUIMICOS'},
    {'entry': 'El Fuerte de la Cuenca', 'category': 'FERTILIZANTES'},
    {'entry': 'Estacion de servicio las mariposas', 'category': 'GASOLINA'},
    {'entry': 'Ferre-electric Vargas', 'category': 'MANO DE OBRA'},
    {'entry': 'Fertilizacion de 13 hectareas con ganchos ', 'category': 'MANO DE OBRA'},
    {'entry': 'Fertisquisa', 'category': 'FERTILIZANTES'},
    {'entry': 'Fitoamina y Takle', 'category': 'AGROQUIMICOS'},
    {'entry': 'FMC Agricola', 'category': 'AGROQUIMICOS'},
    {'entry': 'Gasolina cemento', 'category': 'GASOLINA'},
    {'entry': 'Gasolinera costa verde, S. de R. L.', 'category': 'GASOLINA'},
    {'entry': 'Guardarayas y quemas', 'category': 'COSECHA'},
    {'entry': 'Las granjas, .S.A de C.V.', 'category': 'GASOLINA'},
    {'entry': 'Las granjas, S.A. de C.V.', 'category': 'GASOLINA'},
    {'entry': 'Mano de obra ', 'category': 'MANO DE OBRA'},
    {'entry': 'Mantemiento de Equipo', 'category': 'GASOLINA'},
    {'entry': 'Mantenimiento de Auto', 'category': 'GASOLINA'},
    {'entry': 'Mantenimiento de equipo', 'category': 'GASOLINA'},
    {'entry': 'Mantenimiento de vehiculo', 'category': 'GASOLINA'},
    {'entry': 'Pasaje a Tres Valles, Ver.', 'category': 'MANO DE OBRA'},
    {'entry': 'Pasaje a Tuxepec, Oax.', 'category': 'MANO DE OBRA'},
    {'entry': 'Peaje', 'category': 'MANO DE OBRA'},
    {'entry': 'Preparación del terreno', 'category': 'MANO DE OBRA'},
    {'entry': 'Propinas (Domingo)', 'category': 'COMIDA'},
    {'entry': 'Propinas (Lunes)', 'category': 'COMIDA'},
    {'entry': 'Propinas (Martes)', 'category': 'COMIDA'},
    {'entry': 'Propinas (Miércoles)', 'category': 'COMIDA'},
    {'entry': 'Propinas (Viernes)', 'category': 'COMIDA'},
    {'entry': 'Refaccionaria Alfa', 'category': 'MANO DE OBRA'},
    {'entry': 'Refaccionaria ALS, S.A. de C.V.', 'category': 'MANO DE OBRA'},
    {'entry': 'Refrescos, agua, alcohol, vasos', 'category': 'COMIDA'},
    {'entry': 'Riego (13 - 17)', 'category': 'MANO DE OBRA'},
    {'entry': 'Riego de calles, Yunta y llenado de bolsitas', 'category': 'MANO DE OBRA'},
    {'entry': 'Riego de la semana', 'category': 'MANO DE OBRA'},
    {'entry': 'Riego para el ratón y embolsamiento', 'category': 'MANO DE OBRA'},
    {'entry': 'Riego y Abono (27 -31)', 'category': 'MANO DE OBRA'},
    {'entry': 'Riego y Chofer', 'category': 'MANO DE OBRA'},
    {'entry': 'Riego y Yunta', 'category': 'MANO DE OBRA'},
    {'entry': 'Saco de Azucar', 'category': 'COMIDA'},
    {'entry': 'Semana de chapeo 21 jornales', 'category': 'COSECHA'},
    {'entry': 'Servicio Facil del Sureste, S.A. de C.V.', 'category': 'GASOLINA'},
    {'entry': 'Servicios agropecuarios', 'category': 'AGROQUIMICOS'},
    {'entry': 'Siembra, picado, fertilización, enraizado, liquido bomba', 'category': 'MANO DE OBRA'},
    {'entry': 'Subsuelo, rastra, surcado y acarreo', 'category': 'MANO DE OBRA'},
    {'entry': 'Telefonos de México, S.A.B. de C.V.', 'category': 'MANO DE OBRA'},
    {'entry': 'Ventas, Servicios a equipos forestales STIHL', 'category': 'AGROQUIMICOS'},
    {'entry': 'Vulcanizadora el aguila', 'category': 'GASOLINA'},
    {'entry': 'Corte de caña', 'category': 'COSECHA'},
    {'entry': 'Grupo Byagro, .S.A. de C.V.', 'category': 'FERTILIZANTES'},
    {'entry': 'Semana (12-16) Abono, embolsada y regada de veneno ', 'category': 'MANO DE OBRA'},
    {'entry': 'Anticipo de chapeo, subsuelo, rastra, surco, aarreo, tapado: Sr. José de Jesús Salomón López',
     'category': 'COSECHA'},
    {'entry': 'Farmacon, S.A. de C.V.', 'category': 'OTRO'},
    {'entry': 'Jornales del 14 al 20 de Marzo', 'category': 'MANO DE OBRA'},
    {'entry': 'Siembra (Viviana, Miguel Arturo)', 'category': 'MANO DE OBRA'},
    {'entry': 'Jornales del 18 al 23 de Abril', 'category': 'MANO DE OBRA'},
    {'entry': 'Autopartes Alfa', 'category': 'GASOLINA'},
    {'entry': 'Jornales del 21 al 27 de Marzo', 'category': 'MANO DE OBRA'},
    {'entry': 'Pinturas el Diamante', 'category': 'OTRO'},
    {'entry': 'Jornales del 7 al 12 de Marzo', 'category': 'MANO DE OBRA'},
    {'entry': 'Neto', 'category': 'OTRO'},
    {'entry': 'Refrescos para cortadores', 'category': 'MANO DE OBRA'},
    {'entry': 'Grupo Boxito, S.A. de C.V.', 'category': 'GASOLINA'},
    {'entry': 'Propinas y complemento (VLTG)', 'category': 'COMIDA'},
    {'entry': 'Agroquimicos Solana', 'category': 'AGROQUIMICOS'},
    {'entry': 'Fertilizantes, Agroinsumos y Semillas', 'category': 'FERTILIZANTES'},
    {'entry': 'Nueva Wal Mart de México, S. de R.L. de C.V.', 'category': 'OTRO'},
    {'entry': 'Taller Mecánico Zepeda', 'category': 'GASOLINA'},
    {'entry': 'Jornales del 11 al 17 de Abril', 'category': 'MANO DE OBRA'},
    {'entry': 'Agros de la Cuenca, S.A. de C.V.', 'category': 'AGROQUIMICOS'},
    {'entry': 'Jornal del 13 al 18 de Junio', 'category': 'MANO DE OBRA'},
    {'entry': 'Compra de refrescos para trabajadores del campo', 'category': 'COMIDA'},
    {'entry': 'Vulcanizadora Fallo', 'category': 'GASOLINA'},
    {'entry': '2 viajes de composta', 'category': 'COSECHA'},
    {'entry': 'Tapada, acarreo y regada de caña de Arturo hijo', 'category': 'MANO DE OBRA'},
    {'entry': 'Agroquimica del Tropico', 'category': 'AGROQUIMICOS'},
    {'entry': 'Distribuidora de pvc amsa, S.A. de C.V.', 'category': 'OTRO'},
    {'entry': 'Siembra de caña (arturo, Viviana, Arturo hijo)', 'category': 'MANO DE OBRA'},
    {'entry': 'Tareas de cultivo con gancho y ratreo de guardarayas', 'category': 'MANO DE OBRA'},
    {'entry': 'Checar trasnformador, alta tension, puesta de 2 fusibles (AT)', 'category': 'MANO DE OBRA'},
    {'entry': 'Propina por corte (Playa Margarita)', 'category': 'COMIDA'},
    {'entry': 'Servicio electromecanico "Manolo"', 'category': 'GASOLINA'},
    {'entry': 'Refrescos para jornaleros', 'category': 'COMIDA'},
    {'entry': 'Siembra, acarreo, tapado de caña de Viviana', 'category': 'COSECHA'},
    {'entry': 'Jornal del 23 al 25 de Mayo', 'category': 'MANO DE OBRA'},
    {'entry': 'Deposito en Coppel a trabajadores del campo', 'category': 'MANO DE OBRA'},
    {'entry': 'Trabajadores del campo', 'category': 'MANO DE OBRA'},
    {'entry': '2 Kg Foliar', 'category': 'FERTILIZANTES'},
    {'entry': 'Jornal del 9 al 14 de Mayo', 'category': 'MANO DE OBRA'},
    {'entry': 'Pipa de agua riego VLTG siembra de caña', 'category': 'MANO DE OBRA'},
    {'entry': 'ADO Coatzacoalcos', 'category': 'OTRO'},
    {'entry': 'Ferre3valles del istmo, S.A. de C.V.', 'category': 'OTRO'},
    {'entry': 'Jornal del 16 al 21 de Mayo', 'category': 'MANO DE OBRA'},
    {'entry': 'Mantenimiento a moto bomba', 'category': 'GASOLINA'},
    {'entry': 'Pinturas de la Cuenca', 'category': 'OTRO'},
    {'entry': 'Jornal del 30 de Mayo al 3 de Junio', 'category': 'MANO DE OBRA'},
    {'entry': 'Aceros racma', 'category': 'OTRO'},
    {'entry': 'Riego de Herbicida (VLTG, BTS, ATB)', 'category': 'MANO DE OBRA'},
    {'entry': 'Jornales del 28 de Marzo al 3 de Abril', 'category': 'MANO DE OBRA'},
    {'entry': 'Jornales del 4 al 8 de Abril', 'category': 'MANO DE OBRA'},
    {'entry': 'Promotora Nacional Agropecuaria Mexicana, S.A. de C.V.', 'category': 'AGROQUIMICOS'},
    {'entry': 'Corporacion Novavision', 'category': 'AGROQUIMICOS'},
    {'entry': 'Jornal del 25 al 30 de Abril', 'category': 'MANO DE OBRA'},
    {'entry': 'Coppel, S.A. de C.V. (Acumulador Gonher)', 'category': 'OTRO'},
    {'entry': 'Propinas caña siniestrada AMTG', 'category': 'COMIDA'},
    {'entry': 'Caña siniestrada (despensa)', 'category': 'COMIDA'},
    {'entry': 'Servicio Agrotecnico, S.A. de C.V.', 'category': 'AGROQUIMICOS'},
    {'entry': 'Bebidas para jornaleros', 'category': 'COMIDA'},
    {'entry': 'Jornales del 24 al 30 de Abril', 'category': 'MANO DE OBRA'},
    {'entry': 'Jornal del 6 al 11 de Junio (Rancho Alma Leonor)', 'category': 'MANO DE OBRA'},
    {'entry': 'Rastra, surco, tareas del 1 al 7 de Junio (VLTG/AMTG)', 'category': 'MANO DE OBRA'},
    {'entry': "Servicio electromecanico Manolo']", 'category': 'GASOLINA'},
]


def categorize(entry: str) -> str:
    for i in KNOWN_MAPPINGS:
        if i['entry'].lower() == entry.lower():
            return i['category'], True
    return entry, False
